#!/usr/bin/env node

const config = require('../config');
const del = require('del');
const colors = require('colors');

del([`${config.html.build}/**/*.html`]).then(paths => {
  console.log(colors.green('Html dist files cleaned.'));
});
